<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>R for Health, Behavioral, and Social Scientists</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="R for Health, Behavioral, and Social Scientists">
  <meta name="generator" content="bookdown 0.3 and GitBook 2.6.7">

  <meta property="og:title" content="R for Health, Behavioral, and Social Scientists" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="R for Health, Behavioral, and Social Scientists" />
  
  
  

<meta name="author" content="Tyson S. Barrett">


<meta name="date" content="2017-02-08">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="chapter-5-generalized-linear-models.html">
<link rel="next" href="chapter-7-other-modeling-techniques.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-i"><i class="fa fa-check"></i>Part I</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-ii"><i class="fa fa-check"></i>Part II</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#part-iii"><i class="fa fa-check"></i>Part III</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#download-r-and-rstudio"><i class="fa fa-check"></i>Download R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html"><i class="fa fa-check"></i>Chapter 1: The Basics</a><ul>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#objects-data-types-and-functions"><i class="fa fa-check"></i>Objects, Data Types and Functions</a><ul>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#objects"><i class="fa fa-check"></i>Objects</a></li>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#data-types"><i class="fa fa-check"></i>Data Types</a></li>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#functions"><i class="fa fa-check"></i>Functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#importing-data"><i class="fa fa-check"></i>Importing Data</a><ul>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#delimited-files"><i class="fa fa-check"></i>Delimited Files</a></li>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#other-data-formats"><i class="fa fa-check"></i>Other Data Formats</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#saving-data"><i class="fa fa-check"></i>Saving Data</a></li>
<li class="chapter" data-level="" data-path="chapter-1-the-basics.html"><a href="chapter-1-the-basics.html#conclusions"><i class="fa fa-check"></i>Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html"><i class="fa fa-check"></i>Chapter 2: Manipulating Your Data</a><ul>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#tidy-methods"><i class="fa fa-check"></i>Tidy Methods</a></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#piping"><i class="fa fa-check"></i>Piping</a></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#select-and-filter"><i class="fa fa-check"></i>Select and Filter</a></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#grouping-and-summarizing"><i class="fa fa-check"></i>Grouping and Summarizing</a></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#reshaping"><i class="fa fa-check"></i>Reshaping</a><ul>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#wide-form"><i class="fa fa-check"></i>Wide Form</a></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#long-form"><i class="fa fa-check"></i>Long Form</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#joining-merging"><i class="fa fa-check"></i>Joining (merging)</a><ul>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#inner-join"><i class="fa fa-check"></i>Inner Join</a></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#left-or-right-join"><i class="fa fa-check"></i>Left or Right Join</a></li>
<li class="chapter" data-level="" data-path="chapter-2-manipulating-your-data.html"><a href="chapter-2-manipulating-your-data.html#full-join"><i class="fa fa-check"></i>Full Join</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-3-understanding-and-describing-your-data.html"><a href="chapter-3-understanding-and-describing-your-data.html"><i class="fa fa-check"></i>Chapter 3: Understanding and Describing Your Data</a><ul>
<li class="chapter" data-level="" data-path="chapter-3-understanding-and-describing-your-data.html"><a href="chapter-3-understanding-and-describing-your-data.html#descriptive-statistics"><i class="fa fa-check"></i>Descriptive Statistics</a></li>
<li class="chapter" data-level="" data-path="chapter-3-understanding-and-describing-your-data.html"><a href="chapter-3-understanding-and-describing-your-data.html#visualizations"><i class="fa fa-check"></i>Visualizations</a><ul>
<li class="chapter" data-level="0.0.1" data-path="chapter-3-understanding-and-describing-your-data.html"><a href="chapter-3-understanding-and-describing-your-data.html#using-ggplot2"><i class="fa fa-check"></i><b>0.0.1</b> Using <code class="unnumbered">ggplot2</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html"><i class="fa fa-check"></i>Chapter 4: Basic Analyses</a><ul>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#anova"><i class="fa fa-check"></i>ANOVA</a><ul>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#linear-modeling"><i class="fa fa-check"></i>Linear Modeling</a><ul>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#assumptions-1"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#comparing-models"><i class="fa fa-check"></i>Comparing Models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#when-assumptions-fail"><i class="fa fa-check"></i>When Assumptions Fail</a><ul>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#log-linear-log-log-linear-log-other"><i class="fa fa-check"></i>Log-Linear, Log-Log, Linear-Log, Other</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#interactions"><i class="fa fa-check"></i>Interactions</a><ul>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#interactions-in-anova"><i class="fa fa-check"></i>Interactions in ANOVA</a></li>
<li class="chapter" data-level="" data-path="chapter-4-basic-analyses.html"><a href="chapter-4-basic-analyses.html#interactions-in-linear-regression"><i class="fa fa-check"></i>Interactions in Linear Regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-5-generalized-linear-models.html"><a href="chapter-5-generalized-linear-models.html"><i class="fa fa-check"></i>Chapter 5: Generalized Linear Models</a><ul>
<li class="chapter" data-level="" data-path="chapter-5-generalized-linear-models.html"><a href="chapter-5-generalized-linear-models.html#logistic-regression"><i class="fa fa-check"></i>Logistic Regression</a></li>
<li class="chapter" data-level="" data-path="chapter-5-generalized-linear-models.html"><a href="chapter-5-generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i>Poisson Regression</a><ul>
<li class="chapter" data-level="" data-path="chapter-5-generalized-linear-models.html"><a href="chapter-5-generalized-linear-models.html#gamma"><i class="fa fa-check"></i>Gamma</a></li>
<li class="chapter" data-level="" data-path="chapter-5-generalized-linear-models.html"><a href="chapter-5-generalized-linear-models.html#two-part-or-hurdle-models"><i class="fa fa-check"></i>Two-Part or Hurdle Models</a></li>
<li class="chapter" data-level="" data-path="chapter-5-generalized-linear-models.html"><a href="chapter-5-generalized-linear-models.html#negative-binomial"><i class="fa fa-check"></i>Negative Binomial</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-5-generalized-linear-models.html"><a href="chapter-5-generalized-linear-models.html#beta-regression"><i class="fa fa-check"></i>Beta Regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-6-multilevel-modeling.html"><a href="chapter-6-multilevel-modeling.html"><i class="fa fa-check"></i>Chapter 6: Multilevel Modeling</a><ul>
<li class="chapter" data-level="" data-path="chapter-6-multilevel-modeling.html"><a href="chapter-6-multilevel-modeling.html#gee"><i class="fa fa-check"></i>GEE</a></li>
<li class="chapter" data-level="" data-path="chapter-6-multilevel-modeling.html"><a href="chapter-6-multilevel-modeling.html#mixed-effects"><i class="fa fa-check"></i>Mixed Effects</a></li>
<li class="chapter" data-level="" data-path="chapter-6-multilevel-modeling.html"><a href="chapter-6-multilevel-modeling.html#conclusions-1"><i class="fa fa-check"></i>Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-7-other-modeling-techniques.html"><a href="chapter-7-other-modeling-techniques.html"><i class="fa fa-check"></i>Chapter 7: Other Modeling Techniques</a><ul>
<li class="chapter" data-level="" data-path="chapter-7-other-modeling-techniques.html"><a href="chapter-7-other-modeling-techniques.html#mediation-modeling"><i class="fa fa-check"></i>Mediation Modeling</a></li>
<li class="chapter" data-level="" data-path="chapter-7-other-modeling-techniques.html"><a href="chapter-7-other-modeling-techniques.html#structural-equation-modeling"><i class="fa fa-check"></i>Structural Equation Modeling</a></li>
<li class="chapter" data-level="" data-path="chapter-7-other-modeling-techniques.html"><a href="chapter-7-other-modeling-techniques.html#machine-learning-techniques"><i class="fa fa-check"></i>Machine Learning Techniques</a><ul>
<li class="chapter" data-level="" data-path="chapter-7-other-modeling-techniques.html"><a href="chapter-7-other-modeling-techniques.html#ridge-lasso-and-elastic-net"><i class="fa fa-check"></i>Ridge, Lasso and Elastic Net</a></li>
<li class="chapter" data-level="" data-path="chapter-7-other-modeling-techniques.html"><a href="chapter-7-other-modeling-techniques.html#random-forests"><i class="fa fa-check"></i>Random Forests</a></li>
</ul></li>
<li class="chapter" data-level="0.1" data-path="chapter-7-other-modeling-techniques.html"><a href="chapter-7-other-modeling-techniques.html#conclusions-2"><i class="fa fa-check"></i><b>0.1</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-8-advanced-data-manipulation.html"><a href="chapter-8-advanced-data-manipulation.html"><i class="fa fa-check"></i>Chapter 8: Advanced Data Manipulation</a><ul>
<li class="chapter" data-level="" data-path="chapter-8-advanced-data-manipulation.html"><a href="chapter-8-advanced-data-manipulation.html#your-own-functions"><i class="fa fa-check"></i>Your Own Functions</a></li>
<li class="chapter" data-level="" data-path="chapter-8-advanced-data-manipulation.html"><a href="chapter-8-advanced-data-manipulation.html#vectorized"><i class="fa fa-check"></i>Vectorized</a></li>
<li class="chapter" data-level="" data-path="chapter-8-advanced-data-manipulation.html"><a href="chapter-8-advanced-data-manipulation.html#for-loops"><i class="fa fa-check"></i>For Loops</a></li>
<li><a href="chapter-8-advanced-data-manipulation.html#the-apply-family">The <code>apply</code> family</a><ul>
<li class="chapter" data-level="0.1.1" data-path="chapter-8-advanced-data-manipulation.html"><a href="chapter-8-advanced-data-manipulation.html#speed-comparison"><i class="fa fa-check"></i><b>0.1.1</b> Speed Comparison</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="chapter-8-advanced-data-manipulation.html"><a href="chapter-8-advanced-data-manipulation.html#using-anonymous-functions-in-apply"><i class="fa fa-check"></i><b>0.2</b> Using “Anonymous Functions” in Apply</a></li>
<li class="chapter" data-level="0.3" data-path="chapter-8-advanced-data-manipulation.html"><a href="chapter-8-advanced-data-manipulation.html#conclusions-3"><i class="fa fa-check"></i><b>0.3</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html"><i class="fa fa-check"></i>Chapter 9: Advanced Plotting</a><ul>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#types-of-plots"><i class="fa fa-check"></i>Types of Plots</a><ul>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#boxplots"><i class="fa fa-check"></i>Boxplots</a></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#bar-plots"><i class="fa fa-check"></i>Bar Plots</a></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#line-plots"><i class="fa fa-check"></i>Line Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#color-schemes"><i class="fa fa-check"></i>Color Schemes</a></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#themes"><i class="fa fa-check"></i>Themes</a></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#labels-and-titles"><i class="fa fa-check"></i>Labels and Titles</a></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#facetting"><i class="fa fa-check"></i>Facetting</a></li>
<li class="chapter" data-level="" data-path="chapter-9-advanced-plotting.html"><a href="chapter-9-advanced-plotting.html#conclusions-4"><i class="fa fa-check"></i>Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-10-where-to-go-from-here-and-common-pitfalls.html"><a href="chapter-10-where-to-go-from-here-and-common-pitfalls.html"><i class="fa fa-check"></i>Chapter 10: Where to Go from Here and Common Pitfalls</a><ul>
<li class="chapter" data-level="" data-path="chapter-10-where-to-go-from-here-and-common-pitfalls.html"><a href="chapter-10-where-to-go-from-here-and-common-pitfalls.html#common-pitfalls"><i class="fa fa-check"></i>Common Pitfalls</a></li>
<li class="chapter" data-level="" data-path="chapter-10-where-to-go-from-here-and-common-pitfalls.html"><a href="chapter-10-where-to-go-from-here-and-common-pitfalls.html#quiz"><i class="fa fa-check"></i>Quiz</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Health, Behavioral, and Social Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-6-multilevel-modeling" class="section level1 unnumbered">
<h1>Chapter 6: Multilevel Modeling</h1>
<p>There are two general forms of multilevel modeling:</p>
<ol style="list-style-type: decimal">
<li>Generalized Estimating Equations (GEE)</li>
<li>Mixed effects (ME; i.e., hierarchical linear modeling, multilevel modeling)</li>
</ol>
<p>Several similarities and differences should be noted briefly. As for similarities, they both attempt to control for the lack of independence within clusters, although they do it in different ways. Also, they are both built on linear regression which makes them flexible and powerful at finding relationships in the data.</p>
<p>The differences are subtle but important. First, the interpretation is somewhat different between the two. GEE is a population-averaged (e.g., marginal) model whereas ME is subject specific. In other words, <em>GEE is the average effect</em> while <em>ME is the effect found in the average person</em>. In a linear model, these coefficients are the same but when we use different forms such as logistic or poisson, these can be quite different (although in my experience they generally tell a similar story). Second, ME models are much more complex than the GEE models and can struggle with convergence compared to the GEE. This also means that GEE’s are generally fitted much more quickly. Still the choice of the modeling technique should be driven by your hypotheses and not totally dependent on speed of the computation.</p>
<p>First, if we needed to, we’d reshape our data so that it is ready for the analyses. For both modeling techniques we want our data in long form<a href="#fn16" class="footnoteRef" id="fnref16"><sup>16</sup></a>. What this implies is that each row is an observation. What this actually means about the data depends on the data. For example, if you have repeated measures, then often data is stored in wide form—a row is an individual. To make this long, we want each time point within a person to be a row—a single individual can have multiple rows but each row is a unique observation.</p>
<p>Currently, our data is in long form since we are working within community clusters within this data. So, each row is an observation and each cluster has multiple rows. Note that although these analyses will be within community clusters instead of within subjects (i.e. repeated measures), the overall steps will be the exact same.</p>
<p>This chapter certainly does not cover all of multilevel modeling in <code>R</code>. Entire books are dedicated to that single subject. Rather, we are introducing the methods and the packages that can be used to start using these methods.</p>
<div id="gee" class="section level2 unnumbered">
<h2>GEE</h2>
<p>There are two packages, intimately related, that allow us to perform GEE modeling—<code>gee</code> and <code>geepack</code>. These have some great features and make running a fairly complex model pretty simple. However, as great as they are, there are some annoying shortcomings. We’ll get to a few of them throughout this section.</p>
<p>GEE’s, in general, want a few pieces of information from you. First, the outcome and predictors. This is just as in linear regression and GLM’s. Second, we need to provide a correlation structure. This tells the model the approximate pattern of correlations between the time points or clusters. It also wants a variable that tells the cluster ID’s. Finally, it also wants the family (i.e. the type of distribution).</p>
<p>Since this is not longitudinal, but rather clustered within communities, we’ll assume for this analysis an unstructured correlation structure. It is the most flexible and we have enough power for it here.</p>
<p>For <code>geepack</code> to work, we need to filter out the missing values for the variables that will be in the model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df2 &lt;-<span class="st"> </span>df %&gt;%
<span class="st">  </span><span class="kw">filter</span>(<span class="kw">complete.cases</span>(dep, famsize, sed, race, asthma))</code></pre></div>
<p>Now, we’ll build the model with both packages (just for demonstration). We predict depression with asthma, family size, minutes of sedentary behavior, and the subject’s race.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gee)
fit_gee &lt;-<span class="st"> </span><span class="kw">gee</span>(dep ~<span class="st"> </span>asthma +<span class="st"> </span>famsize +<span class="st"> </span>sed +<span class="st"> </span>race,
               <span class="dt">data =</span> df2,
               <span class="dt">id =</span> df2$sdmvstra,
               <span class="dt">corstr =</span> <span class="st">&quot;unstructured&quot;</span>)</code></pre></div>
<pre><code>##       (Intercept)            asthma           famsize               sed 
##       2.499812759       1.350795482      -0.042520715       0.001369803 
## raceOtherHispanic         raceWhite         raceBlack         raceOther 
##       1.177577726       0.113001672       0.095534279      -0.543096022</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit_gee)$coef</code></pre></div>
<pre><code>##                       Estimate   Naive S.E.    Naive z  Robust S.E.
## (Intercept)        2.495119852 0.2867514061  8.7013343 0.2689564560
## asthma             1.348220554 0.1866015623  7.2251300 0.2135146310
## famsize           -0.039849976 0.0461694874 -0.8631236 0.0457307042
## sed                0.001365896 0.0003362213  4.0624923 0.0003550921
## raceOtherHispanic  1.185033848 0.3074667438  3.8541854 0.3306006443
## raceWhite          0.115201897 0.2532041878  0.4549763 0.2279712534
## raceBlack          0.092164385 0.2625882796  0.3509844 0.2359792297
## raceOther         -0.542714277 0.2809252595 -1.9318814 0.2408902491
##                     Robust z
## (Intercept)        9.2770402
## asthma             6.3144176
## famsize           -0.8714053
## sed                3.8465974
## raceOtherHispanic  3.5844874
## raceWhite          0.5053352
## raceBlack          0.3905614
## raceOther         -2.2529525</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(geepack)
fit_geeglm &lt;-<span class="st"> </span><span class="kw">geeglm</span>(dep ~<span class="st"> </span>asthma +<span class="st"> </span>famsize +<span class="st"> </span>sed +<span class="st"> </span>race,
                     <span class="dt">data =</span> df2,
                     <span class="dt">id =</span> df2$sdmvstra,
                     <span class="dt">corstr =</span> <span class="st">&quot;unstructured&quot;</span>)
<span class="kw">summary</span>(fit_geeglm)</code></pre></div>
<pre><code>## 
## Call:
## geeglm(formula = dep ~ asthma + famsize + sed + race, data = df2, 
##     id = df2$sdmvstra, corstr = &quot;unstructured&quot;)
## 
##  Coefficients:
##                     Estimate    Std.err   Wald Pr(&gt;|W|)    
## (Intercept)        2.5573448  0.2699723 89.731  &lt; 2e-16 ***
## asthma             1.3444243  0.2153281 38.983 4.28e-10 ***
## famsize           -0.0450065  0.0456910  0.970 0.324614    
## sed                0.0013094  0.0003547 13.627 0.000223 ***
## raceOtherHispanic  1.1675544  0.3315368 12.402 0.000429 ***
## raceWhite          0.0797913  0.2295588  0.121 0.728151    
## raceBlack          0.0596164  0.2362489  0.064 0.800774    
## raceOther         -0.5777808  0.2415656  5.721 0.016765 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Estimated Scale Parameters:
##             Estimate Std.err
## (Intercept)    19.49  0.7839
## 
## Correlation: Structure = unstructured  Link = identity 
## 
## Estimated Correlation Parameters:
##           Estimate Std.err
## alpha.1:2  0.12510 0.01653
## alpha.1:3  0.41982 0.10324
## alpha.1:4  2.89847 1.06759
## alpha.1:5 -1.84796 0.20251
## alpha.2:3  0.12222 0.06326
## alpha.2:4 -0.08924 0.20207
## alpha.2:5  0.20431 0.03709
## alpha.3:4 -0.49626 0.11213
## alpha.3:5  0.24935 0.03868
## alpha.4:5 -0.66763 0.08755
## Number of clusters:   4112   Maximum cluster size: 5</code></pre>
<p>The <code>gee</code> package doesn’t directly provide p-values but provides the z-scores, which can be used to find the p-values. The <code>geepack</code> provides the p-values in the way you’ll see in the <code>lm()</code> and <code>glm()</code> functions.</p>
<p>These models are interpreted just as the regular GLM. It has adjusted for the correlations within the clusters and provides valid standard errors and p-values.</p>
</div>
<div id="mixed-effects" class="section level2 unnumbered">
<h2>Mixed Effects</h2>
<p>Mixed effects models require a bit more thinking about the effects. It is called “mixed effects” because we include both fixed and random effects into the model simultaneously. The random effects are those that we don’t necessarily care about the specific values but want to control for it and/or estimate the variance. The fixed effects are those we are used to estimating in linear models and GLM’s.</p>
<p>These are a bit more clear with an example. We will do the same overall model as we did with the GEE but we’ll use ME. To do so, we’ll use the <code>lme4</code> package. In the model below, we predict depression with asthma, family size, minutes of sedentary behavior, and the subject’s race. We have a random intercept (which allows the intercept to vary across clusters).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lme4)
fit_me &lt;-<span class="st"> </span><span class="kw">lmer</span>(dep ~<span class="st"> </span>asthma +<span class="st"> </span>famsize +<span class="st"> </span>sed +<span class="st"> </span>race +<span class="st"> </span>(<span class="dv">1</span> |<span class="st"> </span>cluster),
               <span class="dt">data =</span> df2,
               <span class="dt">REML =</span> <span class="ot">FALSE</span>)
<span class="kw">summary</span>(fit_me)</code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood  [&#39;lmerMod&#39;]
## Formula: dep ~ asthma + famsize + sed + race + (1 | cluster)
##    Data: df2
## 
##      AIC      BIC   logLik deviance df.resid 
##    25805    25869   -12892    25785     4431 
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -1.323 -0.636 -0.355  0.271  5.436 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  cluster  (Intercept)  0.104   0.322   
##  Residual             19.398   4.404   
## Number of obs: 4441, groups:  cluster, 14
## 
## Fixed effects:
##                    Estimate Std. Error t value
## (Intercept)        2.489894   0.302638    8.23
## asthma             1.329994   0.186533    7.13
## famsize           -0.043237   0.046320   -0.93
## sed                0.001433   0.000337    4.26
## raceOtherHispanic  1.283057   0.320393    4.00
## raceWhite          0.009298   0.259480    0.04
## raceBlack          0.168175   0.273351    0.62
## raceOther         -0.540119   0.285494   -1.89
## 
## Correlation of Fixed Effects:
##             (Intr) asthma famsiz sed    rcOthH racWht rcBlck
## asthma      -0.042                                          
## famsize     -0.510 -0.003                                   
## sed         -0.324 -0.044  0.051                            
## rcOthrHspnc -0.557 -0.034  0.052 -0.037                     
## raceWhite   -0.680 -0.038  0.135 -0.148  0.640              
## raceBlack   -0.644 -0.057  0.094 -0.131  0.625  0.776       
## raceOther   -0.580  0.000  0.049 -0.135  0.590  0.725  0.694</code></pre>
<p>You’ll see that there are no p-values provided here. This is because p-values are not well-defined in the ME framework. A good way to test it can be through the <code>anova()</code> function, comparing models. Let’s compare a model with and without <code>asthma</code> to see if the model is significantly better with it in.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit_me1 &lt;-<span class="st"> </span><span class="kw">lmer</span>(dep ~<span class="st"> </span>famsize +<span class="st"> </span>sed +<span class="st"> </span>race +<span class="st"> </span>(<span class="dv">1</span> |<span class="st"> </span>cluster),
               <span class="dt">data =</span> df2,
               <span class="dt">REML =</span> <span class="ot">FALSE</span>)

<span class="kw">anova</span>(fit_me, fit_me1)</code></pre></div>
<pre><code>## Data: df2
## Models:
## fit_me1: dep ~ famsize + sed + race + (1 | cluster)
## fit_me: dep ~ asthma + famsize + sed + race + (1 | cluster)
##         Df   AIC   BIC logLik deviance Chisq Chi Df Pr(&gt;Chisq)    
## fit_me1  9 25853 25911 -12918    25835                            
## fit_me  10 25805 25869 -12892    25785  50.5      1    1.2e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This comparison strongly suggests that <code>asthma</code> is a significant predictor (<span class="math inline">\(\chi^2 = 50.5\)</span>, p &lt; .001). We can do this with both fixed and random effects, as below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit_me2 &lt;-<span class="st"> </span><span class="kw">lmer</span>(dep ~<span class="st"> </span>famsize +<span class="st"> </span>sed +<span class="st"> </span>race +<span class="st"> </span>(<span class="dv">1</span> |<span class="st"> </span>cluster),
               <span class="dt">data =</span> df2,
               <span class="dt">REML =</span> <span class="ot">TRUE</span>)
fit_me3 &lt;-<span class="st"> </span><span class="kw">lmer</span>(dep ~<span class="st"> </span>famsize +<span class="st"> </span>sed +<span class="st"> </span>race +<span class="st"> </span>(<span class="dv">1</span> +<span class="st"> </span>asthma |<span class="st"> </span>cluster),
               <span class="dt">data =</span> df2,
               <span class="dt">REML =</span> <span class="ot">TRUE</span>)
<span class="kw">anova</span>(fit_me2, fit_me3, <span class="dt">refit =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## Data: df2
## Models:
## fit_me2: dep ~ famsize + sed + race + (1 | cluster)
## fit_me3: dep ~ famsize + sed + race + (1 + asthma | cluster)
##         Df   AIC   BIC logLik deviance Chisq Chi Df Pr(&gt;Chisq)    
## fit_me2  9 25879 25937 -12931    25861                            
## fit_me3 11 25847 25917 -12912    25825  36.9      2    9.8e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Here, including random slopes for asthma appears to be significant (<span class="math inline">\(\chi^2 = 36.9\)</span>, p &lt; .001).</p>
<p>Linear mixed effects models converge pretty well. You’ll see that the conclusions and estimates are very similar to that of the GEE. For generalized versions of ME, the convergence can be harder and more picky. As we’ll see below, it complains about large eigenvalues and tells us to rescale some of the variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lme4)
fit_gme &lt;-<span class="st"> </span><span class="kw">glmer</span>(dep2 ~<span class="st"> </span>asthma +<span class="st"> </span>famsize +<span class="st"> </span>sed +<span class="st"> </span>race +<span class="st"> </span>(<span class="dv">1</span> |<span class="st"> </span>cluster),
                 <span class="dt">data =</span> df2,
                 <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control
## $checkConv, : Model failed to converge with max|grad| = 0.0118968 (tol =
## 0.001, component 1)</code></pre>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: very large eigenvalue
##  - Rescale variables?;Model is nearly unidentifiable: large eigenvalue ratio
##  - Rescale variables?</code></pre>
<p>After a quick check, we can see that <code>sed</code> is huge compared to the other variables. If we simply rescale it, using the <code>I()</code> function within the model formula, we can rescale it by 1,000. Here, that is all it needed to converge.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lme4)
fit_gme &lt;-<span class="st"> </span><span class="kw">glmer</span>(dep2 ~<span class="st"> </span>asthma +<span class="st"> </span>famsize +<span class="st"> </span><span class="kw">I</span>(sed/<span class="dv">1000</span>) +<span class="st"> </span>race +<span class="st"> </span>(<span class="dv">1</span> |<span class="st"> </span>cluster),
                 <span class="dt">data =</span> df2,
                 <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)
<span class="kw">summary</span>(fit_gme)</code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: dep2 ~ asthma + famsize + I(sed/1000) + race + (1 | cluster)
##    Data: df2
## 
##      AIC      BIC   logLik deviance df.resid 
##     2672     2729    -1327     2654     4432 
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -0.632 -0.329 -0.295 -0.258  4.971 
## 
## Random effects:
##  Groups  Name        Variance Std.Dev.
##  cluster (Intercept) 0.022    0.148   
## Number of obs: 4441, groups:  cluster, 14
## 
## Fixed effects:
##                   Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        -2.6282     0.2431  -10.81  &lt; 2e-16 ***
## asthma              0.5570     0.1280    4.35  1.4e-05 ***
## famsize            -0.0349     0.0374   -0.93   0.3501    
## I(sed/1000)         0.5877     0.2614    2.25   0.0246 *  
## raceOtherHispanic   0.7517     0.2419    3.11   0.0019 ** 
## raceWhite           0.0965     0.2157    0.45   0.6546    
## raceBlack           0.0505     0.2276    0.22   0.8245    
## raceOther          -0.4689     0.2576   -1.82   0.0687 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) asthma famsiz I(/100 rcOthH racWht rcBlck
## asthma      -0.057                                          
## famsize     -0.491 -0.011                                   
## I(sed/1000) -0.324 -0.041  0.031                            
## rcOthrHspnc -0.655 -0.032  0.045 -0.028                     
## raceWhite   -0.716 -0.036  0.132 -0.148  0.709              
## raceBlack   -0.685 -0.064  0.089 -0.123  0.715  0.780       
## raceOther   -0.575 -0.003  0.047 -0.123  0.608  0.691  0.656</code></pre>
</div>
<div id="conclusions-1" class="section level2 unnumbered">
<h2>Conclusions</h2>
<p>This has been a really brief introduction into a thriving, large field of statistical analyses. These are the general methods for using <code>R</code> to analyze multilevel data. Our next chapter will discuss more modeling techniques in <code>R</code>, including mediation, mixture, and structural equation modeling.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="16">
<li id="fn16"><p>We discuss what this means in much more depth and demonstrate reshaping of data in Chapter 8. It is an important tool to understand if you are working with data in various forms. Although many reshape their data by copying-and-pasting in a spreadsheet, what we present in Chapter 8 is much more efficient, cleaner, less error-prone, and replicatable.<a href="chapter-6-multilevel-modeling.html#fnref16">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter-5-generalized-linear-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-7-other-modeling-techniques.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
